### ISSUE TITLE
Use gradle.properties specifies the Java home

### ISSUE THREAD

**Issue by xeemoo** [YunaBraska/gradle-java-fix#1]
I get error "Unsupported class file major version XX" too. I fixed it by setting the environment variable in `gradle.properties`."
```properties
org.gradle.java.home=/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home
```

**Comment by YunaBraska** [comment]
Yes, you can do that. But that’s not a fix, that’s a workaround. With that, you make your projects system dependent. Which is not what you want using Java. Everyone would need to have the same path, version and distribution. Even on Windows.

Technology shouldn’t make us think and save time. That’s what my script does. You can just run is as an Alias command (https://github.com/YunaBraska/gradle-java-fix#install-as-global-command--alias) and it will figure out everything for you.
Things should just work out of the box, else it's a pain and not a support. 

I think gradle should l get the path automatically as you set the Java version already on the `build.gradle` file. Also, Java is backwards compatible, so there shouldn’t be any issues at all. Quality is something else. 😉

**Comment by xeemoo** [comment]
I think you're referring to this ? [[Consuming Toolchains](https://docs.gradle.org/7.0/userguide/toolchains.html#sec:consuming)](https://docs.gradle.org/7.0/userguide/toolchains.html#sec:consuming) . But it only works on Gradle 7.0 and above :)

**Comment by YunaBraska** [comment]
You can define the Java version also in older gradle versions. Just the syntax changes. Anyway, my script is just an addon to find run gradle with the Java version depending on your gradle definition. Gradle looks shiny but it has still a long way to go.
